SELECT 
    'test' as MODEL_SOURCE, 
    'test' as MODEL_SEQUENCE, 
    TO_CHAR(MODEL_TIMESTAMP) as MODEL_TIMESTAMP, 
    MODEL_SOURCE_DATA, 
    MODEL_NAME, 
    MODEL_OUTPUT, 
    PATIENT_TYPE, 
    PATIENT_TIMEFRAME, 
    PATIENT_STRATA, 
    STAY_KEY, 
    STAY_KEY_SEQ, 
    '1' as NUM_OF_PATIENT, 
    '1' as STAY_RATE, 
    TO_CHAR(STAY_START_DATE) as STAY_START_DATE, 
    TO_CHAR(STAY_END_DATE) as STAY_END_DATE 
FROM CPM_MODEL_COMMON_FORMAT;